# Generated by Django 3.0.5 on 2020-04-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200409_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_imageurl',
            field=models.CharField(default="{% static 'main/images/ext.jpg'%}", max_length=200),
        ),
    ]
