# Generated by Django 3.0.5 on 2020-04-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200409_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_link',
            field=models.CharField(default='https://en.wikipedia.org/wiki/BP', max_length=200),
        ),
    ]
