# Generated by Django 3.0.5 on 2020-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tutorial_tutorial_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_link',
            field=models.CharField(default='https://en.wikipedia.org/wiki/BP', max_length=200, null=True),
        ),
    ]
