# Generated by Django 3.0.5 on 2020-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200413_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_link',
            field=models.CharField(blank=True, default='https://en.wikipedia.org/wiki/BP', max_length=200, null=True),
        ),
    ]
