# Generated by Django 3.0.5 on 2020-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200413_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_link',
            field=models.CharField(blank=True, default='https://en.wikipedia.org/wiki/Royal_Dutch_Shell', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_title',
            field=models.CharField(default='Company Name', max_length=200),
        ),
    ]
