# Generated by Django 3.0.5 on 2020-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200413_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_link',
            field=models.CharField(blank=True, default='https://en.wikipedia.org/wiki/ConocoPhillips', max_length=200, null=True),
        ),
    ]
