# Generated by Django 3.0.5 on 2020-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200413_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='pol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='sub',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
