# Generated by Django 3.0.5 on 2020-04-26 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200425_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(default='Company Name', max_length=200)),
                ('Customer_content', models.TextField(blank=True, null=True)),
                ('Customer_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('Customer_imageurl', models.CharField(default='static/main/images/no-image.jpg', max_length=200)),
                ('Customer_link', models.CharField(blank=True, default='https://en.wikipedia.org/wiki/ConocoPhillips', max_length=200, null=True)),
                ('pol', models.FloatField(blank=True, null=True)),
                ('sub', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
